<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZXksdaB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZXksdaB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZXksdaB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZXksdaB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZXksdaB\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZXksdaB',
    'container.build_id' => '67bfd2d3',
    'container.build_time' => 1659819696,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZXksdaB');
